services:
  backend:
    image: eclipse-temurin:24-alpine
    container_name: tichtic-backend
    working_dir: /app
    volumes:
      - ./tichtic-backend/target:/app
      - ./tichtic-backend/config:/app/config
    command: ["java", "-jar", "/app/tichtic-0.0.1-SNAPSHOT.jar","--spring.profiles.active=default,podman", "--spring.external-config.location=/app/config/application-podman.yml"]
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default,podman
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started
    networks:
      - tichtic-network
  redis:
    image: redis:alpine
    container_name: tichtic-redis
    ports:
      - "6379:6379"
    networks:
      - tichtic-network
  database:
    image: postgres:18
    container_name: tichtic-database
    environment:
      POSTGRES_USER: tichtic
      POSTGRES_PASSWORD: tichtic
      POSTGRES_DB: tichtic
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tichtic"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tichtic-network
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - tichtic-network
  kafka:
    image: wurstmeister/kafka:latest
    container_name: tichtic-kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper
    networks:
      - tichtic-network
  apache:
    image: httpd:alpine
    container_name: tichtic-apache
    volumes:
      - ./tichtic-ui:/usr/local/apache2/htdocs/
    ports:
      - "8081:80"
    networks:
      - tichtic-network

networks:
  tichtic-network:
    driver: bridge

x-podman:
    in_pod: false