spring:
  application:
    name: tichtic
  datasource:
    url: jdbc:postgresql://localhost:5432/tichtic
    username: tichtic
    password: tichtic
  liquibase:
    enabled: true
    change-log: classpath:database/master-changelog.xml
    default-schema: public
  redis:
    data:
      host: localhost
      port: 6379
  cache:
    type: redis
  kafka:
    bootstrap-servers: localhost:9092
shortener:
  defaultExpireInDays: 7
  urlPrefix: http://localhost:8080

logging:
  level:
    org:
      springframework:
        cache: TRACE
