spring:
  application:
    name: tichtic
  datasource:
    url: jdbc:mysql://localhost:3306/tichtic
    username: tichtic
    password: tichtic
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
  kafka:
    bootstrap-servers: localhost:9092
shortener:
  defaultExpireInDays: 7
  urlPrefix: http://localhost:8080

logging:
  level:
    org:
      springframework:
        cache: TRACE
