spring:
  application:
    name: tichtic
  datasource:
    url: jdbc:postgresql://database:5432/tichtic
    username: tichtic
    password: tichtic
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
  kafka:
    bootstrap-servers: kafka:9092
shortener:
  defaultExpireInDays: 7
  urlPrefix: http://localhost:8080

logging:
  level:
    org:
      springframework:
        cache: TRACE
        secutrity: DEBUG